### ISSUE TITLE
Use fully qualified name for type constructor

### ISSUE THREAD

**Issue by turlando** [turlando/purescm#30]
In car of dotted pair representing an algebraic data type

**Comment by turlando** [comment]
I'm more convinced not to do this one.

The rationale behind this card was to allow better Scheme-PureScript integration by providing metadata about the ADTs to the Lisp level.

For example, the type:

```purescript
module My.Awesome.Module where
data Foo = Bar Int | Baz String
```

would be translated into:

```scheme
(define Bar (lambda (x) ('My.Awesome.Module.Bar . x)))
(define Baz (lambda (x) ('My.Awesome.Module.Baz . x)))
```

So that if a Scheme function would be passed a `Foo` it could universally distinguish it from any other type in the system and not just between `Baz` and `Baz`.

But let's at how does the JS implementation translate the following code:

```purescript
data Foo = Bar Int
doubleFoo (Bar i) = i + i
```

```javascript
var Bar = (function () {
    function Bar(value0) {
        this.value0 = value0;
    };
    Bar.create = function (value0) {
        return new Bar(value0);
    };
    return Bar;
})();

var doubleFoo = function (v) {
    return v.value0 + v.value0 | 0;
};
```

As you can see the compiler doesn't emit any check to verify that the value being passed is a `Bar`, and it does indeed make sense since there is only one possible constructor for `Foo` and the type checker won't allow to pass doubleFoo any type other than `Foo`.

So if you agree with me @f-f I'd rather hijack this issue and convert it to something like "Don't emit constructor checks when dealing with types with a single constructor" in order to match the JS behavior.

**Comment by f-f** [comment]
@turlando sounds great! :+1:
